name: Push to Docker Hub
on:
  push:
    branches: [staging]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            dockerfile: backend/Dockerfile
            image: xiandadu/oliver-backend-api
          - name: pdf
            dockerfile: machine_learning/pdf_processor/Dockerfile
            image: xiandadu/oliver-pdf-service
          - name: rag
            dockerfile: machine_learning/rag_system/Dockerfile
            image: xiandadu/oliver-rag-service
          - name: agent
            dockerfile: machine_learning/ai_agents/Dockerfile
            image: xiandadu/oliver-agent-service
          - name: frontend
            dockerfile: frontend/Dockerfile
            image: xiandadu/oliver-frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }} 
          push: true
          tags: |
            ${{ matrix.image }}:${{ github.sha }}
            ${{ matrix.image }}:latest
