name: Push to Docker Hub
on:
  push:
    branches: [staging]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            context: ./backend
            image: xiandadu/oliver-backend-api
          - name: pdf
            context: ./machine_learning/pdf_processor
            image: xiandadu/oliver-pdf-service
          - name: rag
            context: ./machine_learning/rag_system
            image: xiandadu/oliver-rag-service
          - name: agent
            context: ./machine_learning/ai_agents
            image: xiandadu/oliver-agent-service
          - name: frontend
            context: ./frontend
            image: xiandadu/oliver-frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ matrix.image }}:${{ github.sha }}
            ${{ matrix.image }}:latest
